# Generated by Django 5.2.1 on 2025-06-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image',
            new_name='image_large',
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
